name: CI

on: [pull_request]
  # push:
  #   branches:
  #     - main

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: testing, CCOV: true}
          - {ROS_DISTRO: humble, ROS_REPO: main}
    env:
      CXXFLAGS: >-
        -Wall -Wextra
      CODE_COVERAGE: codecov.io
      TARGET_CMAKE_ARGS: >
        -DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld
        -DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=lld
        -DCMAKE_MODULE_LINKER_FLAGS=-fuse-ld=lld
        -DCMAKE_BUILD_TYPE=${{ matrix.env.CCOV && 'Debug' || 'Release'}}
        -DCMAKE_CXX_FLAGS="-Werror $CXXFLAGS${{ matrix.env.CCOV && ' --coverage -O2 -fno-omit-frame-pointer'}}"
      UPSTREAM_CMAKE_ARGS: "-DCMAKE_CXX_FLAGS=''"
      DOWNSTREAM_CMAKE_ARGS: -DCMAKE_CXX_FLAGS="-Wall -Wextra"
      ADDITIONAL_DEBS: lld
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: ici
        uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
      - name: Generate codecov report for ros2_kitti_core
        working-directory: ${{ github.workspace }}/target_ws
        env: ${{matrix.env}}
        if: always() && matrix.env.CCOV && steps.ici.outputs.target_test_results == '0'
        run: |
          apt-get -qq update
          apt-get install -q -y lcov
          lcov --initial --no-external --capture --directory ./target_ws --output-file ./target_ws/base.info --include "*/ros2_kitti_core/include/ros2_kitti_core/*" --include "*/ros2_kitti_core/src/*" --exclude "*/build/*" --exclude "*/install/*" --exclude "*/test/*"
          lcov --no-external --capture --directory ./target_ws --output-file ./test.info --include "*/ros2_kitti_core/*" --exclude "*/build/*" --exclude "*/target_ws/install/*" --exclude "*/test/*"
          lcov --add-tracefile ./base.info --add-tracefile ./test.info --output-file ./coverage.info
      - name: Upload codecov report
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/target_ws/coverage.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
